# Generated by Django 4.0.3 on 2022-04-02 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_api', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paypal', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('resume', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=150)),
                ('datehour', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('drink', models.ManyToManyField(to='partycipe.cocktail')),
                ('organisate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partycipe.party')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
